Models/Agent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Moot.Models
{
    public class Agent
    {
        public int ID { get; set; }
        [Required]
        [Display(Name = "Agent Name")]
        [StringLength(50)]
        public string AgentName { get; set; }

        [StringLength(70)]
        public string Title { get; set; }
        public ICollection<PublishedProperty>? PublishedProperties { get; set; }

    }
}

Controllers/AgentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Moot.Models.LibraryViewModels;
using Moot.Data;
using Moot.Models;
using Microsoft.AspNetCore.Authorization;

namespace Moot.Controllers
{
    [Authorize(Roles = "OnlySales")]
    public class AgentsController : Controller
    {
        private readonly LibraryContext _context;

        public AgentsController(LibraryContext context)
        {
            _context = context;
        }

        // GET: Agents
        [AllowAnonymous]
        public async Task<IActionResult> Index(int? id, int? propertyID)
        {
            var viewModel = new AgentIndexData();

            viewModel.Agents = await _context.Agent
            .Include(p => p.PublishedProperties)
                    .ThenInclude(pb => pb.Property)
                .ThenInclude(b => b.Owner) // Include autorii cărților
                .Include(p => p.PublishedProperties)
                    .ThenInclude(pb => pb.Property)
                .ThenInclude(b => b.Offers)
                    .ThenInclude(o => o.Client) // Include clienții pentru comenzi
                .AsNoTracking()
                .OrderBy(p => p.AgentName)
                .ToListAsync();

            if (id != null)
            {
                ViewData["AgentID"] = id.Value;
                Agent agent = viewModel.Agents.Where(
                i => i.ID == id.Value).Single();
                viewModel.Properties = agent.PublishedProperties.Select(s => s.Property);
            }
            if (propertyID != null)
            {
                ViewData["PropertyID"] = propertyID.Value;
                viewModel.Offers = viewModel.Properties.Where(x => x.ID == propertyID).Single().Offers;
            }
            return View(viewModel);
        }

        // GET: Agents/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var agent = await _context.Agent
                .FirstOrDefaultAsync(m => m.ID == id);
            if (agent == null)
            {
                return NotFound();
            }

            return View(agent);
        }

        // GET: Agents/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Agents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,AgentName,Title")] Agent agent)
        {
            if (ModelState.IsValid)
            {
                _context.Add(agent);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(agent);
        }

        // GET: Agents/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var agent = await _context.Agent
            .Include(i => i.PublishedProperties).ThenInclude(i => i.Property)
            .AsNoTracking()
            .FirstOrDefaultAsync(m => m.ID == id);
            if (agent == null)
            {
                return NotFound();
            }
            PopulatePublishedPropertyData(agent);
            return View(agent);
        }
        private void PopulatePublishedPropertyData(Agent agent)
        {
            var allProperties = _context.Property;
            var publisherBooks = new HashSet<int>(agent.PublishedProperties.Select(c => c.PropertyID));
            var viewModel = new List<PublishedPropertyData>();
            foreach (var property in allProperties)
            {
                viewModel.Add(new PublishedPropertyData
                {
                    PropertyID = property.ID,
                    PropertyType = property.PropertyType,
                    IsAvailable = publisherBooks.Contains(property.ID)
                });
            }
            ViewData["Books"] = viewModel;
        }

        // POST: Agents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, string[] selectedProperties)
        {
            if (id == null)
            {
                return NotFound();
            }
            var agentToUpdate = await _context.Agent
            .Include(i => i.PublishedProperties)
            .ThenInclude(i => i.Property)
            .FirstOrDefaultAsync(m => m.ID == id);
            if (await TryUpdateModelAsync<Agent>(
            agentToUpdate,
            "",
            i => i.AgentName, i => i.Title))
            {
                UpdatePublishedPropertyData(selectedProperties, agentToUpdate);
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateException /* ex */)
                {
                    ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists, ");
                }
                return RedirectToAction(nameof(Index));
            }
            UpdatePublishedPropertyData(selectedProperties, agentToUpdate);
            PopulatePublishedPropertyData(agentToUpdate);
            return View(agentToUpdate);
        }
        private void UpdatePublishedPropertyData(string[] selectedProperties, Agent agentToUpdate)
        {
            if (selectedProperties == null)
            {
                agentToUpdate.PublishedProperties = new List<PublishedProperty>();
                return;
            }
            var selectedPropertiesHS = new HashSet<string>(selectedProperties);
            var publishedProperties = new HashSet<int>
            (agentToUpdate.PublishedProperties.Select(c => c.Property.ID));
            foreach (var property in _context.Property)
            {
                if (selectedPropertiesHS.Contains(property.ID.ToString()))
                {
                    if (!publishedProperties.Contains(property.ID))
                    {
                        agentToUpdate.PublishedProperties.Add(new PublishedProperty
                        {
                            AgentID = agentToUpdate.ID,
                            PropertyID = property.ID
                        });
                    }
                }
                else
                {
                    if (publishedProperties.Contains(property.ID))
                    {
                        PublishedProperty propertyToRemove = agentToUpdate.PublishedProperties.FirstOrDefault(i
                        => i.PropertyID == property.ID);
                        _context.Remove(propertyToRemove);
                    }
                }
            }
        }

        // GET: Agents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var agent = await _context.Agent
                .FirstOrDefaultAsync(m => m.ID == id);
            if (agent == null)
            {
                return NotFound();
            }

            return View(agent);
        }

        // POST: Agents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var agent = await _context.Agent.FindAsync(id);
            if (agent != null)
            {
                _context.Agent.Remove(agent);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AgentExists(int id)
        {
            return _context.Agent.Any(e => e.ID == id);
        }
    }
}

Controllers/PropertiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Humanizer.Localisation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Moot.Data;
using Moot.Models;
using static System.Reflection.Metadata.BlobBuilder;

namespace Moot.Controllers
{
    [Authorize(Roles = "OnlySales")]
    public class PropertiesController : Controller
    {
        private readonly LibraryContext _context;

        public PropertiesController(LibraryContext context)
        {
            _context = context;
        }

        // GET: Properties
        [AllowAnonymous]
        public async Task<IActionResult> Index(
        string sortOrder,
        string currentFilter,
        string searchString,
        int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["PropertyTypeSortParm"] = String.IsNullOrEmpty(sortOrder) ? "PropertyType_desc" : "";
            ViewData["PriceSortParm"] = sortOrder == "Price" ? "price_desc" : "Price";
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;
            var properties = from b in _context.Property
                        .Include(b => b.Neighborhood)
                        join a in _context.Owner on b.OwnerID equals a.ID
                        join n in _context.Neighborhood on b.NeighborhoodID equals n.ID
                        select new PropertyViewModel
                        {
                            ID = b.ID,
                            PropertyType = b.PropertyType,
                            Price = b.Price,
                            FullName = a.FullName,
                            NeighborhoodName = n.Name
                        };
            if (!String.IsNullOrEmpty(searchString))
            {
                properties = properties.Where(s => s.PropertyType.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "PropertyType_desc":
                    properties = properties.OrderByDescending(b => b.PropertyType);
                    break;
                case "Price":
                    properties = properties.OrderBy(b => b.Price);
                    break;
                case "price_desc":
                    properties = properties.OrderByDescending(b => b.Price);
                    break;
                default:
                    properties = properties.OrderBy(b => b.PropertyType);
                    break;
            }
            int pageSize = 5;
            return View(await PaginatedList<PropertyViewModel>.CreateAsync(properties.AsNoTracking(),
            pageNumber ?? 1, pageSize));
        }

        // GET: Properties/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var property = await _context.Property
                .Include(b => b.Neighborhood)
                .Include(b => b.Owner)
                .Include(navigationPropertyPath: s => s.Offers)
                .ThenInclude(e => e.Client)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);
            if (property == null)
            {
                return NotFound();
            }

            ViewData["OwnerID"] = new SelectList(_context.Set<Owner>(), "ID", "FullName");
            ViewData["NeighborhoodID"] = new SelectList(_context.Set<Neighborhood>(), "ID", "Name");
            return View(property);
        }

        // GET: Properties/Create
        public IActionResult Create()
        {
            ViewData["NeighborhoodID"] = new SelectList(_context.Set<Neighborhood>(), "ID", "Name");
            ViewData["OwnerID"] = new SelectList(_context.Set<Owner>(), "ID", "FullName");
            return View();
        }

        // POST: Properties/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PropertyType,Owner,Price")] Property @property)
        {
            try
            {
            if (ModelState.IsValid)
            {
                _context.Add(property);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            }
            catch (DbUpdateException /* ex*/)
            {
                ModelState.AddModelError("", "Unable to save changes. " +
                "Try again, and if the problem persists ");
            }

            // ViewBag.Owners = new SelectList(_context.Owner, "ID", "FirstName");

            // ViewData["NeighborhoodID"] = new SelectList(_context.Set<Neighborhood>(), "ID", "ID", property.NeighborhoodID);
            return View(property);
        }

        // GET: Properties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var property = await _context.Property.FindAsync(id);
            if (property == null)
            {
                return NotFound();
            }

            ViewData["OwnerID"] = new SelectList(_context.Set<Owner>(), "ID", "FullName");
            ViewData["NeighborhoodID"] = new SelectList(_context.Set<Neighborhood>(), "ID", "Name");
            return View(property);
        }

        // POST: Properties/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var bookToUpdate = await _context.Property.FirstOrDefaultAsync(s => s.ID == id);
            if (await TryUpdateModelAsync<Property>(bookToUpdate, "", s => s.OwnerID, s => s.PropertyType, s => s.Price))
            {
                try
                {
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException /* ex */)
                {
                    ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists");
                }
            }
            ViewData["OwnerID"] = new SelectList(_context.Owner, "ID", "FullName",
           bookToUpdate.OwnerID);
            return View(bookToUpdate);
        }

        // GET: Properties/Delete/5
        public async Task<IActionResult> Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var property = await _context.Property
                .Include(b => b.Neighborhood)
                .Include(b => b.Owner)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);

            if (@property == null)
            {
                return NotFound();
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] =
                "Delete failed. Try again";
            }
            return View(@property);
        }

        // POST: Properties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @property = await _context.Property.FindAsync(id);
            if (@property == null)
            {
                return RedirectToAction(nameof(Index));
            }

            try
            {
                _context.Property.Remove(property);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException /* ex */)
            {
                return RedirectToAction(nameof(Delete), new { id = id, saveChangesError = true });
            }
        }

        private bool PropertyExists(int id)
        {
            return _context.Property.Any(e => e.ID == id);
        }

    }
}

Views/Agents/Create.cshtml
@model Moot.Models.Agent

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Agent</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AgentName" class="control-label"></label>
                <input asp-for="AgentName" class="form-control" />
                <span asp-validation-for="AgentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Agents/Delete.cshtml
@model Moot.Models.Agent

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Agent</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AgentName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AgentName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Agents/Details.cshtml
@model Moot.Models.Agent

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Agent</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AgentName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AgentName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Agents/Edit.cshtml
@model Moot.Models.Agent

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Agent</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="AgentName" class="control-label"></label>
                <input asp-for="AgentName" class="form-control" />
                <span asp-validation-for="AgentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Agents/Index.cshtml
@model Moot.Models.LibraryViewModels.AgentIndexData

@{
	ViewData["Title"] = "Publishers";
}
<h2>Agents</h2>
<p>
	<a asp-action="Create">Create New</a>
</p>
<table class="table">
	<thead>
		<tr>
			<th>Agent Name</th>
			<th>Title</th>
			<th>Properties</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model.Agents)
		{
			string selectedRow = "";
			if (item.ID == (int?)ViewData["AgentID"])
			{
				selectedRow = "success";
			}
			<tr class="@selectedRow">
				<td>
					@Html.DisplayFor(modelItem => item.AgentName)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Title)
				</td>
				<td>
					@foreach (var property in item.PublishedProperties)
					{
						<a asp-action="Details" asp-controller="Properties" asp-route-id="@property.Property.ID">
							@property.Property.ID
						</a>
						@: @property.Property.PropertyType <br />
					}
				</td>
				<td>
					<a asp-action="Index" asp-route-id="@item.ID">Select</a> |
					<a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
					<a asp-action="Details" asp-route-id="@item.ID">Details</a> |
					<a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
				</td>
			</tr>
		}
	</tbody>
</table>

@if (Model.Properties != null)
{
	<h3>Property Published by Selected Agent</h3>
	<table class="table">
		<tr>
			<th></th>
			<th>Title</th>
			<th>Author</th>
			<th>Price</th>
		</tr>
		@foreach (var item in Model.Properties)
		{
			string selectedRow = "";
			if (item.ID == (int?)ViewData["BookID"])
			{
				selectedRow = "success";
			}
			<tr class="@selectedRow">
				<td>
					@Html.ActionLink("Select", "Index", new { propertyID = item.ID })
				</td>
				<td>
					@item.PropertyType
				</td>
				<td>
					@item.Owner
				</td>
				<td>
					@($"{item.Price:F2} €")
				</td>
			</tr>
		}
	</table>
}
@if (Model.Offers != null)
{
	<h3>Clients that have offered the Selected Property</h3>
	<table class="table">
		<thead>
			<tr>
				<th>Name</th>
				<th>Offer Date</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var order in Model.Offers)
			{
				<tr>
					<td>@order.Client.Name</td>
					<td>@(order.OfferDate.HasValue ? order.OfferDate.Value.ToString("dd/MM/yyyy HH:mm:ss") : "No Date")</td>
				</tr>
			}
		</tbody>
	</table>
}